name: Compilar

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install SDL2
      run: sudo apt-get install libsdl2-dev
    - name: compile
      run: make
